from collections.abc import Callable, Iterable
from typing import Any

class SearchStrategy[T]:
    def map[U](self, pack: Callable[[T], U]) -> SearchStrategy[U]: ...
    def flatmap[U](self, expand: Callable[[T], SearchStrategy[U]]) -> SearchStrategy[U]: ...
    def __or__[U](self, other: SearchStrategy[U]) -> SearchStrategy[T | U]: ...


def builds[T](target: Callable[..., T], *args: SearchStrategy[Any], **kwargs: SearchStrategy[Any]) -> SearchStrategy[T]: ...
def sampled_from[T](elements: Iterable[T]) -> SearchStrategy[T]: ...
def integers(*, min_value: int | None = ..., max_value: int | None = ...) -> SearchStrategy[int]: ...
def lists[T](elements: SearchStrategy[T], *, min_size: int = ..., max_size: int | None = ...) -> SearchStrategy[list[T]]: ...